apiVersion: v1
kind: Pod
metadata:
  name: grafana-0
  namespace: grafana-saans
spec:
  containers:
  - name: grafana
    image: grafana/grafana:9.3.6
    volumeMounts:
    - name: storage
      mountPath:
        - /etc/grafana/grafana.ini
        - /var/lib/grafana
        - /var/run/secrets/kubernetes.io/serviceaccount
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: storage
