apiVersion: v1
kind: Pod
metadata:
  name: grafana-0
  namespace: grafana-saans
spec:
  containers:
  - name: my-container
    image: my-image
    volumeMounts:
    - name: my-volume
      mountPath: /path/to/mount
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc
